# TODO

jobs:
  # -------------------------- test --------------------------

  flutter_test_web:
    TODO

  flutter_test_windows:
    name: Flutter integration test on Windows
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FRB_MAIN_FLUTTER_VERSION }}
          architecture: x64
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.FRB_MAIN_RUST_VERSION }}

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm

      - run: just flutter_example_with_flutter_integration_test

      - name: Install Corrosion
        run: |
          cd ..
          git clone --branch v0.4.4 --depth 1 https://github.com/corrosion-rs/corrosion.git
          cmake -Scorrosion -Bbuild -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          cmake --install build --config Release
          echo "C:\Program Files (x86)\Corrosion" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Run Flutter integration tests explicitly requiring Corrosion
        working-directory: ./frb_example/with_flutter
        run: |
          mv -Force windows/rust.require.cmake windows/rust.cmake
          just flutter_example_with_flutter_integration_test

  # should re-open after Flutter fixes this infra timeout issue #1225
  # flutter_test_macos:
  #   name: Flutter integration test on MacOS
  #   runs-on: macos-11

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         cache: true
  #         # TODO should be 3.7.3 but has a weird bug currently
  #         # https://github.com/fzyzcjy/flutter_rust_bridge/pull/1023#issuecomment-1415852845
  #         flutter-version: ${{ env.FRB_MAIN_FLUTTER_VERSION }}
  #         architecture: x64
  #     - uses: dtolnay/rust-toolchain@stable
  #       with:
  #         toolchain: ${{ env.FRB_MAIN_RUST_VERSION }}

  #     - run: just flutter_example_with_flutter_integration_test

  flutter_test_linux:
    name: Flutter integration test on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FRB_MAIN_FLUTTER_VERSION }}
          architecture: x64
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.FRB_MAIN_RUST_VERSION }}

      - name: Setup headless display

        uses: pyvista/setup-headless-display-action@v1

      - run: just install_prerequisite_for_integration_test_linux

      - run: just flutter_example_with_flutter_integration_test

      - run: just install_corrosion_linux
      - name: Run Flutter integration tests explicitly requiring Corrosion
        working-directory: ./frb_example/with_flutter
        run: |
          set -euxo pipefail
          mv linux/rust.require.cmake linux/rust.cmake
          just flutter_example_with_flutter_integration_test
