name: flutter_rust_bridge_internal
description: Tools for development of flutter_rust_bridge (not for end users)
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.1.1

dev_dependencies:
  build_runner: ^2.2.0
  lints: ^2.1.0
  test: ^1.24.0
