# See `pure_dart` example for comments on the configs
rust_input: rust/src/api/**/*.rs
dart_output: lib/src/rust
c_output: frb_generated.h
dump_all: true
default_external_library_loader_web_prefix: http://localhost:8080/pkg/
