name: frb_example_dart_minimal
description: flutter rust bridge example
version: 1.0.0
publish_to: none
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  lints: ^2.0.1
  flutter_rust_bridge:
    path: ../../frb_dart
  native_assets_cli: ^0.2.0
dev_dependencies:
  test: ^1.21.4
  build_runner: ^2.4.4
  ffigen: ^9.0.0
