name: flutter_rust_bridge_utils
description: Utility for flutter_rust_bridge, may publish later
version: 1.0.0
repository: https://github.com/fzyzcjy/flutter_rust_bridge
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  args: ^2.3.1
  build_cli_annotations: ^2.1.0
  js: ^0.6.4
  meta: ^1.3.0
  path: ^1.8.1
dev_dependencies:
  build_cli: ^2.2.0
  build_runner: ^2.2.0
  ffigen: ">=8.0.0"
  flutter_lints: ^3.0.1
  test: ^1.16.8
