name: flutter_rust_bridge
description: High-level memory-safe binding generator for Flutter/Dart <-> Rust
version: 1.82.4
repository: https://github.com/fzyzcjy/flutter_rust_bridge
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  args: ^2.3.1
  build_cli_annotations: ^2.1.0
  js: ^0.6.4
  meta: ^1.3.0
  # required by integration_test
  path: ^1.8.1
  puppeteer: ^3.1.1
  shelf: ^1.3.2
  shelf_static: ^1.1.1
  shelf_web_socket: ^1.0.2
  uuid: ^4.1.0
  web_socket_channel: ^2.2.0
  tuple: ^2.0.1
dev_dependencies:
  build_cli: ^2.2.0
  build_runner: ^2.2.0
  ffigen: ">=8.0.0"
  flutter_lints: ^3.0.1
  test: ^1.16.8
executables:
  flutter_rust_bridge_serve: serve
