name: Build Dart ASAN

on:
  workflow_dispatch: {}
  push: {}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      # to avoid wasting github action's time of doing repeated work while we setup everything
      # we should directly connect and firstly try all commands ad-hoc
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
      - name: Sleep forever
        run: sleep 1000000
