name: CI

on:
  push:
    branches:
      - master
  pull_request: { }
  workflow_dispatch: { }

env:
  CARGO_TERM_COLOR: always
  FRB_MAIN_RUST_VERSION: 1.74.0
  FRB_MAIN_DART_VERSION: 3.4.0
  FRB_MAIN_FLUTTER_VERSION: 3.22.0

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # ----------------------------------- deploy -----------------------------------

  test_dart_sanitizer:
    name: 'Test :: Dart :: Sanitizer'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - asan
        package:
          - frb_example--dart_minimal
          - frb_example--pure_dart
          - frb_example--pure_dart_pde
          - frb_example--deliberate_bad
          # no need for `frb_example--dart_build_rs`

    steps:
      # setup
      - uses: catchpoint/workflow-telemetry-action@v1
        with:
          comment_on_pr: false
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.FRB_MAIN_RUST_VERSION }}
          components: rustfmt
      - run: |-
          rustup toolchain install nightly
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
          architecture: x64

      # execute
      - run: ./frb_internal test-dart-sanitizer --package ${{ matrix.package }} --sanitizer ${{ matrix.sanitizer }}

