name: ❔

on:
  workflow_call:
    inputs:
      flutter_version:
        required: false
        type: string
        # TODO should be 3.7.3 but has a weird bug currently
        # https://github.com/fzyzcjy/flutter_rust_bridge/pull/1023#issuecomment-1415852845
        default: "3.3.10"
      rust_version:
        required: false
        type: string
        default: "1.64.0"

jobs:
  flutter_macos_test:
    runs-on: macos-11

    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ inputs.rust_version }}

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ inputs.flutter_version }}
          architecture: x64

      - uses: actions/checkout@v2

      - name: Enable platform support
        run: flutter config --enable-macos-desktop

      - name: Install Flutter dependencies
        working-directory: ./frb_example/with_flutter
        run: flutter pub get

      - name: Run Flutter integration tests
        working-directory: ./frb_example/with_flutter
        run: flutter test -d macos integration_test/main.dart --verbose
