name: GitHub Pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - "website/**"
      - "frb_example/gallery/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # setup
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: website/yarn.lock
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"
      - name: Setup `mdbook-mermaid`
        run: cargo install mdbook-mermaid

      # execute
      - run: ./frb_internal generate-website

      # deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/merged_target
