# NOTE: Please keep in sync with `ci.yaml`
#
# Ensure doc's steps can work correctly, where users use the released versions
# instead of the code in master branch
name: Post-Release

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0,30 * * * *"

env:
  CARGO_TERM_COLOR: always
  FRB_MAIN_RUST_VERSION: 1.74.0
  FRB_MAIN_DART_VERSION: 3.2.0
  FRB_MAIN_FLUTTER_VERSION: 3.16.0

jobs:
  test_mimic_quickstart:
    name: 'Test :: MimicQuickstart'
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - windows-2019
          - macos-11
          - ubuntu-20.04
        codegen_install_mode:
          - cargo-install
          - cargo-binstall
          - scoop
          - homebrew

    steps:
      # setup
      - uses: catchpoint/workflow-telemetry-action@v1
        with:
          comment_on_pr: false
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.FRB_MAIN_RUST_VERSION }}
          components: rustfmt
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FRB_MAIN_FLUTTER_VERSION }}
          architecture: x64
      - uses: cargo-bins/cargo-binstall@main
      - if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression

      # execute
      - run: ./frb_internal post-release-mimic-quickstart --codegen-install-mode ${{ matrix.codegen_install_mode }}
